/*
Ory Identities API

This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.

API version:
Contact: office@ory.sh
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateTestLoginFlowBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTestLoginFlowBody{}

// CreateTestLoginFlowBody struct for CreateTestLoginFlowBody
type CreateTestLoginFlowBody struct {
	// ID of the OIDC provider to test. Must match a provider configured on the project that serves this request.
	ProviderId           string `json:"provider_id"`
	AdditionalProperties map[string]interface{}
}

type _CreateTestLoginFlowBody CreateTestLoginFlowBody

// NewCreateTestLoginFlowBody instantiates a new CreateTestLoginFlowBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTestLoginFlowBody(providerId string) *CreateTestLoginFlowBody {
	this := CreateTestLoginFlowBody{}
	this.ProviderId = providerId
	return &this
}

// NewCreateTestLoginFlowBodyWithDefaults instantiates a new CreateTestLoginFlowBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTestLoginFlowBodyWithDefaults() *CreateTestLoginFlowBody {
	this := CreateTestLoginFlowBody{}
	return &this
}

// GetProviderId returns the ProviderId field value
func (o *CreateTestLoginFlowBody) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateTestLoginFlowBody) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CreateTestLoginFlowBody) SetProviderId(v string) {
	o.ProviderId = v
}

func (o CreateTestLoginFlowBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTestLoginFlowBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider_id"] = o.ProviderId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateTestLoginFlowBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTestLoginFlowBody := _CreateTestLoginFlowBody{}

	err = json.Unmarshal(data, &varCreateTestLoginFlowBody)

	if err != nil {
		return err
	}

	*o = CreateTestLoginFlowBody(varCreateTestLoginFlowBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "provider_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateTestLoginFlowBody struct {
	value *CreateTestLoginFlowBody
	isSet bool
}

func (v NullableCreateTestLoginFlowBody) Get() *CreateTestLoginFlowBody {
	return v.value
}

func (v *NullableCreateTestLoginFlowBody) Set(val *CreateTestLoginFlowBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTestLoginFlowBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTestLoginFlowBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTestLoginFlowBody(val *CreateTestLoginFlowBody) *NullableCreateTestLoginFlowBody {
	return &NullableCreateTestLoginFlowBody{value: val, isSet: true}
}

func (v NullableCreateTestLoginFlowBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTestLoginFlowBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
